[package]
name = "dead-man-switch"
version = "0.1.0"
edition = "2021"
authors = ["Jose Storopoli <jose@storopoli.io>"]
description = "A simple no-BS Dead Man's Switch"
license = "AGPL-3.0-only"
readme = "README.md"

[dependencies]

[profile.release]
opt-level = "z"   # Optimized for size, use 3 for speed
lto = true        # Enable Link Time Optimization
codegen-units = 1 # Reduced to increase optimizations
panic = "abort"   # Abort on panic
strip = "symbols" # Strip symbols from binary
